apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  namespace: web_app
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql/data
