apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-volume-claim
  namespace: quiz-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
