apiVersion: v1
kind: Service
metadata:
  namespace: web_app
  name: postgresql-svc
  labels:
    app: postgresql
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresql
