name: Application CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build with Docker Compose
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        docker-compose build

    - name: Test with Docker Compose
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        docker-compose up -d
        docker-compose down
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1  

    - name: Tag, and Push the Image to Amazon ECR
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        FRONTEND_ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        BACKEND_ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        
        
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $FRONTEND_ECR_REGISTRY
        docker tag frontend $FRONTEND_ECR_REGISTRY/frontend-repo:latest
        docker push $FRONTEND_ECR_REGISTRY/frontend-repo:latest
        
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $BACKEND_ECR_REGISTRY
        docker tag backend $BACKEND_ECR_REGISTRY/backend-repo:latest
        docker push $BACKEND_ECR_REGISTRY/backend-repo:latest
